### ISSUE TITLE
Feat: Add an estimation of price in USD

### ISSUE THREAD

**Issue by Maxou44** [lum-network/wallet#59]
Hello,

Can you add an estimation of the price in the wallet based on the current price displayed on https://lum.network/ ?

Have a great day,
Maxime

**Comment by Segfaultd** [comment]
Hi @Maxou44 and thank you for that suggestion. Would you mind giving an example of where you want it to be added? Is it displaying the raw price or displaying the LUM amounts in fiat currency?
