### ISSUE TITLE
Add a "max" button

### ISSUE THREAD

**Issue by krutouchel** [lum-network/wallet#79]
Hi guys,

What do you think about adding a "max" button to the LUM wallet?

![photo](https://user-images.githubusercontent.com/93942801/168443877-37eeccc7-0913-4699-b66d-c63c4cc661c6.jpg)

**Comment by Segfaultd** [comment]
Hello @krutouchel,

That looks a good idea. Thank you for suggesting!

We will investigate it and come back later with a timeframe.

Regards
