### ISSUE TITLE
Bug: e.amount.split is not a function

### ISSUE THREAD

**Issue by bryanmlyr** [lum-network/wallet#94]
Hello 😄,

When you try to undelegate a floating point amount, an error occur `e.amount.split is not a function`
![Screenshot 2022-12-05 at 10 57 18](https://user-images.githubusercontent.com/25261144/205608376-7823e4ed-7048-4f03-9358-3890b547f43d.png)

**Comment by Segfaultd** [comment]
Hello @bryanmlyr and thank you for the report. We scheduled this internally and one of our engineer will pickup the fix ASAP.

Thanks!
